### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ttexan1** [GeekProducts/attendance#3]
1. これはScovilleのipアドレス？
https://github.com/GeekProducts/attendance/blob/bf00d113ec64edd930d8079d68b781601c7c3d06/app/controllers/application_controller.rb#L5

2. この数字は何？
https://github.com/GeekProducts/attendance/blob/bf00d113ec64edd930d8079d68b781601c7c3d06/app/controllers/application_controller.rb#L14

3. GoogleDriveWrapperはいつ使っているの?
https://github.com/GeekProducts/attendance/blob/bf00d113ec64edd930d8079d68b781601c7c3d06/app/models/google_drive_wrapper.rb#L1

4. apiはどこから呼び出しているの？これもauthenticationつけたほうがいいと思うけど
https://github.com/GeekProducts/attendance/blob/bf00d113ec64edd930d8079d68b781601c7c3d06/app/controllers/api/v1/courses_controller.rb#L1

**Comment by Hiroo-Miyata** [comment]
> これはScovilleのipアドレス？
そうです。

> この数字は何？
エラー処理としてIPアドレスを入れてましたが、結局使っていませんでした。

> GoogleDriveWrapperはいつ使っているの?
使っていません。

> apiはどこから呼び出しているの？これもauthenticationつけたほうがいいと思うけど
google spreadsheetとの連携で使っています。

**Comment by ttexan1** [comment]
ありがとう!
